"""empty message

Revision ID: 0fd97196e97d
Revises: 2b309edd9bf0
Create Date: 2021-03-11 07:44:42.946592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd97196e97d'
down_revision = '2b309edd9bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping_message', sa.String(), nullable=True))
    op.add_column('order', sa.Column('total_amounts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_amounts')
    op.drop_column('order', 'shipping_message')
    # ### end Alembic commands ###
