"""empty message

Revision ID: 1638ae2a6871
Revises: 0fd97196e97d
Create Date: 2021-03-11 07:54:02.370217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1638ae2a6871'
down_revision = '0fd97196e97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('receiver_name', sa.String(length=128), nullable=True))
    op.add_column('order', sa.Column('receiver_phone', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'receiver_phone')
    op.drop_column('order', 'receiver_name')
    # ### end Alembic commands ###
