"""empty message

Revision ID: 2b309edd9bf0
Revises: 
Create Date: 2021-03-11 07:37:46.348372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b309edd9bf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('orderer_id', sa.String(length=128), nullable=True),
    sa.Column('orderer_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
