"""empty message

Revision ID: 366ee4dc6f2e
Revises: a745764443df
Create Date: 2021-03-28 21:55:04.266643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366ee4dc6f2e'
down_revision = 'a745764443df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('orderer_id', sa.String(
                        length=128), nullable=True),
                    sa.Column('orderer_name', sa.String(
                        length=128), nullable=True),
                    sa.Column('receiver_name', sa.String(
                        length=128), nullable=True),
                    sa.Column('receiver_phone', sa.String(
                        length=128), nullable=True),
                    sa.Column('shipping_zip_code', sa.String(
                        length=128), nullable=True),
                    sa.Column('shipping_address1', sa.String(), nullable=True),
                    sa.Column('shipping_address2', sa.String(), nullable=True),
                    sa.Column('shipping_message', sa.String(), nullable=True),
                    sa.Column('total_amounts', sa.Integer(), nullable=True),
                    sa.Column('state', sa.Enum('PAYMENT_WAITING', 'PREPARING', 'SHIPPED', 'DELIVERING',
                                               'DELIVERY_COMPLETED', 'CANCELED', name='orderstate'), nullable=True),
                    sa.Column('order_date', sa.DateTime(), server_default=sa.text(
                        '(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('detail', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order_line',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.String(
                        length=128), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_line')
    op.drop_table('product')
    op.drop_table('order')
    # ### end Alembic commands ###
