"""empty message

Revision ID: 6f94e9bd91ed
Revises: 1638ae2a6871
Create Date: 2021-03-11 07:57:14.194281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f94e9bd91ed'
down_revision = '1638ae2a6871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_date')
    # ### end Alembic commands ###
