"""empty message

Revision ID: 91d1c0880b18
Revises: 600e9697a9ea
Create Date: 2021-04-17 19:49:59.389189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d1c0880b18'
down_revision = '600e9697a9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_amounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_amounts', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
