"""empty message

Revision ID: cdcafae2a8f6
Revises: 6f94e9bd91ed
Create Date: 2021-03-11 08:06:28.862464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcafae2a8f6'
down_revision = '6f94e9bd91ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping_address1', sa.String(), nullable=True))
    op.add_column('order', sa.Column('shipping_address2', sa.String(), nullable=True))
    op.add_column('order', sa.Column('shipping_zip_code', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'shipping_zip_code')
    op.drop_column('order', 'shipping_address2')
    op.drop_column('order', 'shipping_address1')
    # ### end Alembic commands ###
